medInfo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('search.urls'))
]

search/urls.py
from django.urls import path
from search import views

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
    path('isi/<str:doc>/', views.isi, name="isi")
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
import os
import re
from datetime import datetime

from django.shortcuts import render

from .letor import rerank_search_results


def index(request):
    start_time = datetime.now()
    totalTime = None
    sumDocs = None
    num_results = request.GET.get('num_results', 10)  # Default adalah 10

    query = request.GET.get('search-bar')

    if query == None or query == "":

        context = {
            'query': query,
            'flag': 0
        }
        return render(request, 'search/index.html', context)

    else:

        result = {}

        # ini yang pake bm25 doang!!!!

        sorted_did_scores = rerank_search_results(query, int(num_results))
        for (score, doc) in sorted_did_scores:
            print(f"{doc:30} {score:>.3f}")

        if len(sorted_did_scores) == 0:  # jika tidak ada hasil

            totalTime = 0
            sumDocs = 0

            context = {
                'query': query,
                'flag': 1,
                'totalTime': totalTime,
                'sumDocs': sumDocs
            }

            return render(request, 'search/index.html', context)

        else:  # jika ada hasil

            for score, doc in sorted_did_scores:
                path_doc = os.path.dirname(__file__) + "\\" + doc.lstrip('.')
                with open(path_doc, encoding='utf-8') as file:
                    for line in file:
                        parts = doc.split('/')
                        collection_info = f"Collections {parts[2]}: {parts[3]}"
                        result[collection_info] = line

            end_time = datetime.now()
            totalTime = end_time - start_time

            sumDocs = len(result)

            context = {
                'query': query,
                'flag': 2,
                'result': result,
                'totalTime': totalTime,
                'sumDocs': sumDocs
            }

            return render(request, 'search/index.html', context)


def isi(request, doc):
    title = doc
    content = None
    digits = re.findall(r'\d+', doc)

    url_path = os.path.dirname(__file__) + '/collections/' + '/'.join(digits) + '.txt'
    with open(url_path, encoding='utf-8') as file:
        for line in file:
            content = line

    title1 = title.split(":")[1]
    title2 = title.split(":")[0]

    context = {
        'title': title,
        'title1': title1,
        'title2': title2,
        'content': content,
    }

    return render(request, 'search/isi.html', context)

search/templates/search/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">    
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% block meta %}
  {% endblock meta %}
</head>

  
</body>
{% block content %}
{% endblock content %}  

  
</html>

search/templates/search/index.html
{% extends 'search/base.html' %}

{% block meta %}
    <title>KnowInfo</title>
{% endblock meta %}

{% block content %}
{% if flag == 0 %} 
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6 text-center">
            <span style="color: green; font-size: 70px;">Know</span>
            <span style="color: black; font-size: 70px;">Info</span>
            <form method="GET" action="{% url 'search:index' %}" class="d-flex mt-4">
                <div class="col-8 me-2">
                    <input name="search-bar" id="search-bar" class="form-control rounded-pill me-2" type="search" placeholder="Search" aria-label="Search" value="{{ query|default_if_none:'' }}">
                </div>
                <div class="col-2 me-2">
                    <select name="num_results" class="form-select rounded-pill me-2">
                        <option value="5">5</option>
                        <option value="10" selected>10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                </div>
                <button class="btn btn-outline-success rounded-pill" >
                    <i class="fa fa-search" style="font-size:24px"></i>
                </button>
            </form>
        </div>
    </div>
</div>
{% elif flag == 1 %} 
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6 text-center">
            <span style="color: green; font-size: 70px;">Know</span>
            <span style="color: black; font-size: 70px;">Info</span>
            <form method="GET" action="{% url 'search:index' %}" class="d-flex mt-4">
                <div class="col-8 me-2">
                    <input name="search-bar" id="search-bar" class="form-control rounded-pill me-2" type="search" placeholder="Search" aria-label="Search" value="{{ query|default_if_none:'' }}">
                </div>
                <div class="col-2 me-2">
                    <select name="num_results" class="form-select rounded-pill me-2">
                        <option value="5">5</option>
                        <option value="10" selected>10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                </div>
                <button class="btn btn-outline-success rounded-pill" >
                    <i class="fa fa-search" style="font-size:24px"></i>
                </button>
            </form>
            <p class="text-danger mt-3"><br>Sorry, there is no result:(</p>
        </div>
    </div>
</div>
{% else %} 
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: rgba(255, 255, 255, 0.7); z-index: 1000;">
    <div class="container mt-4">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'search:index' %}">
            <span style="color: green; font-size: 40px;">Know</span>
            <span style="color: black; font-size: 40px;">Info</span>
        </a>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
            <form class="form-inline" style="width: 600px;" method="GET" action="{% url 'search:index' %}">
                <div class="input-group">
                    <div class="col-8 me-2">
                        <input name="search-bar" id="search-bar" class="form-control rounded-pill me-2" type="search" placeholder="Search" aria-label="Search" value="{{ query|default_if_none:'' }}">
                    </div>
                    <div class="col-2 me-2">
                        <select name="num_results" class="form-select rounded-pill me-2">
                            <option value="5">5</option>
                            <option value="10" selected>10</option>
                            <option value="20">20</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                    </div>
                    <div class="input-group-append">
                        <button class="btn btn-outline-success rounded-pill" type="submit">
                            <i class="fa fa-search" style="font-size:24px"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</nav>

<!-- list hasil result nya -->
<div class="container" style="margin-top: 130px;">
    <div class="text-right text-muted" style="margin-left: 100px;">
        About {{ sumDocs }} result{% if sumDocs != 1 %}s{% endif %} ({{ totalTime }} seconds)
    </div>
    <br>

    {% for doc, content in result.items %}
    <a href="{% url 'search:isi' doc %}" style="text-decoration: none;">
        <div class="card rounded shadow mx-auto" style="width: 1000px;">
            <div class="card-body">
                <h3 style="color: green;">{{ doc }}</h3>
                <p>{{ content|truncatechars:300 }}</p>
            </div>
        </div>
    </a>
    <br>
    {% endfor %}

</div>

{% endif %} 
{% endblock content %}

search/templates/search/isi.html
{% extends 'search/base.html' %}

{% block meta %}
    <title>{{ doc_id }}</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: rgba(255, 255, 255, 0.7); z-index: 1000;">
    <div class="container mt-4">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'search:index' %}">
            <span style="color: green; font-size: 40px;">med</span>
            <span style="color: black; font-size: 40px;">Info</span>
        </a>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
            <form class="form-inline" style="width: 600px;" method="GET" action="{% url 'search:index' %}">
                <div class="input-group">
                    <input name="search-bar" id="search-bar" class="form-control rounded-pill" type="search" placeholder="Search" aria-label="Search" value="{{ query|default_if_none:'' }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-success rounded-pill" type="submit">
                            <i class="fa fa-search" style="font-size:24px"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</nav>

<!-- contoh collection 0/12.txt -->
<div class="container" style="margin-top: 150px;">
    <!-- Title container -->
    <div class="title-container justify-content-center" style="text-align: center;">
        <h1 style="color:green">{{ title1 }}</h1>
        <h5>{{ title2 }}</h5>
    </div>

    <br>
    <br>

    <!-- Content container -->
    <div class="content-container" style="margin-left: 130px; margin-right: 130px;">
        <p>{{ content }}</p>
    </div>
</div>

{% endblock content %}